(()=>{"use strict";
const $=id=>document.getElementById(id);
const money=n=>new Intl.NumberFormat("de-DE",{style:"currency",currency:"EUR"}).format(Number(n)||0);
const pad=n=>String(n).padStart(2,"0");
const ym=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}`;
const today=new Date();
let month=ym(today);
let state={version:2,plans:{},expenses:[],recurring:[],savings:{current:0,monthly:0,goal:0}};
try{const raw=localStorage.getItem("money-plan-v2");if(raw)state=JSON.parse(raw)}catch(e){}
const categories=["Food & groceries","Eating out","Shopping","Leisure","Health","Subscriptions","Other variable","Housing","Utilities & bills","Transport","Family","Other fixed"];
const cat=$("category"),rcat=$("rCat");categories.forEach(x=>{cat.add(new Option(x,x));rcat.add(new Option(x,x))});
const variable=[["food","Food & groceries","pFood"],["eating","Eating out","pEating"],["shopping","Shopping","pShopping"],["leisure","Leisure","pLeisure"],["health","Health","pHealth"],["subscriptions","Subscriptions","pSubscriptions"],["otherVar","Other variable","pOtherVar"]];
function save(){state.version=2;localStorage.setItem("money-plan-v2",JSON.stringify(state))}
function num(id){return Math.max(0,Number($(id).value)||0)}
function getPlan(){if(!state.plans[month])state.plans[month]={income:0,housing:0,bills:0,transport:0,family:0,otherFixed:0,savings:0,food:0,eating:0,shopping:0,leisure:0,health:0,subscriptions:0,otherVar:0};return state.plans[month]}
function monthDates(key){const [y,m]=key.split("-").map(Number);const start=new Date(y,m-1,1);const end=new Date(y,m,1);return{start,end,days:new Date(y,m,0).getDate()}}
function monthExpenses(){return state.expenses.filter(e=>e.date.startsWith(month))}
function recurringIncome(){return state.recurring.filter(x=>x.active&&x.type==="income").reduce((a,x)=>a+x.amount,0)}
function recurringExpense(){return state.recurring.filter(x=>x.active&&x.type==="expense").reduce((a,x)=>a+x.amount,0)}
function effectivePlan(){const p=getPlan();const x={...p};if(x.income===0)x.income=recurringIncome();x.bills+=recurringExpense();return x}
function fixed(p){return p.housing+p.bills+p.transport+p.family+p.otherFixed}
function variablePool(p){return p.food+p.eating+p.shopping+p.leisure+p.health+p.subscriptions+p.otherVar}
function showScreen(id){document.querySelectorAll(".screen").forEach(s=>s.classList.toggle("active",s.id===id));document.querySelectorAll(".nav button").forEach(b=>b.classList.toggle("active",b.dataset.screen===id));if(id==="expenses")renderExpenses();if(id==="plan"){loadPlan();renderRecurring()}if(id==="savingsScreen")loadSavings();render()}
document.querySelectorAll(".nav button,[data-screen]").forEach(b=>b.addEventListener("click",()=>showScreen(b.dataset.screen)));
document.querySelectorAll("[data-month]").forEach(b=>b.addEventListener("click",()=>{const d=new Date(month+"-01T12:00:00");d.setMonth(d.getMonth()+Number(b.dataset.month));month=ym(d);render();loadPlan();renderExpenses()}));
$("fab").onclick=()=>{showScreen("expenses");$("amount").focus()};
$("help").onclick=()=>alert("Money Plan V2 uses a savings-first budget. It reserves fixed commitments and your savings target, then turns the remaining variable budget into a daily allowance. Actual spending is compared with that allowance and projected to month-end. Use Settings → Export backup regularly.");
$("expenseForm").onsubmit=e=>{e.preventDefault();const amount=num("amount");if(!amount)return;state.expenses.push({id:Date.now(),date:$("date").value,amount,category:$("category").value,note:$("note").value.trim()});save();e.target.reset();$("date").value=new Date().toISOString().slice(0,10);toast("Expense added");render();renderExpenses()};
function loadPlan(){const p=getPlan();const map={income:"pIncome",housing:"pHousing",bills:"pBills",transport:"pTransport",family:"pFamily",otherFixed:"pOtherFixed",savings:"pSavings",food:"pFood",eating:"pEating",shopping:"pShopping",leisure:"pLeisure",health:"pHealth",subscriptions:"pSubscriptions",otherVar:"pOtherVar"};Object.entries(map).forEach(([k,id])=>$(id).value=p[k]||0)}
$("savePlan").onclick=()=>{const p=getPlan();Object.assign(p,{income:num("pIncome"),housing:num("pHousing"),bills:num("pBills"),transport:num("pTransport"),family:num("pFamily"),otherFixed:num("pOtherFixed"),savings:num("pSavings"),food:num("pFood"),eating:num("pEating"),shopping:num("pShopping"),leisure:num("pLeisure"),health:num("pHealth"),subscriptions:num("pSubscriptions"),otherVar:num("pOtherVar")});save();toast("Monthly plan saved");render()};
$("recForm").onsubmit=e=>{e.preventDefault();const amount=num("rAmount"),name=$("rName").value.trim();if(!amount||!name)return;state.recurring.push({id:Date.now(),name,amount,type:$("rType").value,category:$("rCat").value,active:true});save();e.target.reset();renderRecurring();toast("Recurring item added");render()};
function renderRecurring(){$("recurring").innerHTML=state.recurring.map((r,i)=>`<div class="rec-row"><div><b>${esc(r.name)}</b><div class="muted">${r.type==="income"?"Income":"Expense"} · ${esc(r.category)}</div></div><div><b>${money(r.amount)}</b> <button class="delete" data-rec="${i}">Delete</button></div></div>`).join("")||`<span class="muted">No recurring items.</span>`;document.querySelectorAll("[data-rec]").forEach(b=>b.onclick=()=>{state.recurring.splice(+b.dataset.rec,1);save();renderRecurring();render()})}
$("saveSavings").onclick=()=>{state.savings={current:num("sCurrent"),monthly:num("sMonthly"),goal:num("sGoal")};save();toast("Savings strategy saved");render()}
function loadSavings(){$("sCurrent").value=state.savings.current||0;$("sMonthly").value=state.savings.monthly||0;$("sGoal").value=state.savings.goal||0}
function render(){const p=effectivePlan(),ex=monthExpenses(),spent=ex.reduce((a,e)=>a+e.amount,0),commit=fixed(p),varBudget=variablePool(p),safe=Math.max(0,p.income-commit-p.savings),d=monthDates(month),isCurrent=month===ym(today),day=isCurrent?today.getDate():d.days,remainingDays=isCurrent?Math.max(1,d.days-day+1):d.days,projected=spent/(Math.max(1,day))*d.days,projectedSavings=p.income-commit-projected,monthEnd=p.income-commit-projected;const variableSpent=ex.filter(e=>["Food & groceries","Eating out","Shopping","Leisure","Health","Subscriptions","Other variable"].includes(e.category)).reduce((a,e)=>a+e.amount,0);const remainingVariable=Math.max(0,safe-variableSpent);const daily=remainingDays>0?remainingVariable/remainingDays:0;
$("month").textContent=new Date(month+"-01T12:00:00").toLocaleDateString("en-GB",{month:"long",year:"numeric"});$("expenseMonth").textContent=$("month").textContent;$("planMonth").textContent=$("month").textContent;
$("income").textContent=money(p.income);$("fixed").textContent=money(commit);$("savings").textContent=money(p.savings);$("spent").textContent=money(spent);$("safeSpend").textContent=money(safe);$("dailyAllowance").textContent=money(daily);
const used=safe?Math.min(100,variableSpent/safe*100):0;$("safeBar").style.width=used+"%";$("safeMessage").textContent=safe?`${money(variableSpent)} of your ${money(safe)} variable-spending pool has been used.`:"Set income, commitments and savings in Plan.";
const allowanceToday=ex.filter(e=>e.date===new Date().toISOString().slice(0,10)).reduce((a,e)=>a+e.amount,0);const delta=daily-allowanceToday;$("dailyStatus").className="mini-status "+(delta>=0?"ok":"bad");$("dailyStatus").textContent=delta>=0?`${money(delta)} left today`:`${money(Math.abs(delta))} over today's allowance`;
$("projected").textContent=money(projected);$("projectedSave").textContent=money(projectedSavings);$("monthEnd").textContent=money(monthEnd);
const badge=$("forecastBadge");badge.className="badge "+(projected<=safe+commit?"good":"bad");badge.textContent=projected<=safe+commit?"On track":"Over plan";
$("forecastText").textContent=p.income?`At the current spending pace, you are projected to spend ${money(projected)} this month. Your planned savings after that would be ${money(projectedSavings)}.`:"Enter a monthly plan to activate the forecast.";
const sums={};ex.forEach(e=>sums[e.category]=(sums[e.category]||0)+e.amount);$("budgetList").innerHTML=variable.map(([key,label])=>{const budget=p[key],actual=sums[label]||0,pct=budget?Math.min(120,actual/budget*100):0;return `<div class="budget"><div class="budget-label"><span>${label}</span><b>${money(actual)} / ${money(budget)}</b></div><div class="bar"><i class="${actual>budget?"over":""}" style="width:${Math.min(100,pct)}%"></i></div></div>`}).join("");
$("recent").innerHTML=ex.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,6).map(e=>`<div class="expense-row"><div class="expense-meta"><b>${esc(e.category)}</b><span>${esc(e.date)}${e.note?" · "+esc(e.note):""}</span></div><span class="amount">${money(e.amount)}</span></div>`).join("")||`<span class="muted">No expenses yet.</span>`;
const plannedTotal=commit+p.savings+varBudget;const unallocated=p.income-plannedTotal;$("planReality").innerHTML=`<div class="forecast-grid"><div><span>Income</span><b>${money(p.income)}</b></div><div><span>Commitments</span><b>${money(commit)}</b></div><div><span>Savings</span><b>${money(p.savings)}</b></div></div><p class="${unallocated<0?"negative":"positive"}"><b>${unallocated<0?"Plan exceeds income by ":"Unallocated buffer: "}${money(Math.abs(unallocated))}</b></p>${unallocated<0?'<p class="negative">This plan cannot work without reducing costs, savings or increasing income.</p>':'<p class="muted">That buffer is deliberately unassigned. Keeping a buffer is safer than planning every euro.</p>'}`;
const s=state.savings,goal=s.goal,cur=s.current,monthly=s.monthly,gp=goal?Math.min(100,cur/goal*100):0;$("goalValue").textContent=money(cur);$("goalBar").style.width=gp+"%";$("goalText").textContent=goal&&monthly&&cur<goal?`${Math.ceil((goal-cur)/monthly)} months to goal at the current contribution.`:goal&&cur>=goal?"Goal reached.":"Set a goal and monthly contribution.";renderProjection()}
function renderExpenses(){$("expenseList").innerHTML=monthExpenses().slice().sort((a,b)=>b.date.localeCompare(a.date)).map(e=>`<div class="expense-row"><div class="expense-meta"><b>${esc(e.category)}</b><span>${esc(e.date)}${e.note?" · "+esc(e.note):""}</span></div><div><span class="amount">${money(e.amount)}</span><button class="delete" data-del="${e.id}">Delete</button></div></div>`).join("")||`<span class="muted">No expenses for this month.</span>`;document.querySelectorAll("[data-del]").forEach(b=>b.onclick=()=>{state.expenses=state.expenses.filter(e=>String(e.id)!==b.dataset.del);save();renderExpenses();render()})}
function renderProjection(){const s=state.savings,rows=[];for(let i=1;i<=12;i++){const v=s.current+s.monthly*i;rows.push(`<div class="budget"><div class="budget-label"><span>Month ${i}</span><b>${money(v)}</b></div><div class="bar"><i style="width:${s.goal?Math.min(100,v/s.goal*100):0}%"></i></div></div>`)}$("projection").innerHTML=rows.join("")||`<span class="muted">Set your savings strategy above.</span>`}
$("export").onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`money-plan-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url);toast("Backup exported")};
$("importBtn").onclick=()=>$("importFile").click();$("importFile").onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!x.expenses||!x.plans)throw new Error();state=x;save();loadPlan();loadSavings();render();renderExpenses();renderRecurring();toast("Backup restored")}catch(_){alert("That backup file is not valid.")}};r.readAsText(f)};
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function toast(t){$("toast").textContent=t;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),1700)}
$("date").value=today.toISOString().slice(0,10);loadPlan();loadSavings();renderRecurring();render();renderExpenses();
if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js").catch(()=>{});
})();