(()=>{"use strict";
const $=id=>document.getElementById(id);
const money=n=>new Intl.NumberFormat("de-DE",{style:"currency",currency:"EUR"}).format(Number(n)||0);
const pad=n=>String(n).padStart(2,"0");
const cycleKeyFromDate=d=>{const x=new Date(d);if(x.getDate()<25)x.setMonth(x.getMonth()-1);return `${x.getFullYear()}-${pad(x.getMonth()+1)}`};
const cycleStart=key=>{const [y,m]=key.split("-").map(Number);return new Date(y,m-1,25,12)};
const cycleEnd=key=>{const s=cycleStart(key);return new Date(s.getFullYear(),s.getMonth()+1,24,12)};
const cycleLabel=key=>cycleEnd(key).toLocaleDateString("de-DE",{month:"long",year:"numeric"});
const iso=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const displayDate=d=>`${pad(d.getDate())}-${pad(d.getMonth()+1)}-${d.getFullYear()}`;
const displayIsoDate=x=>{const d=new Date(`${x}T12:00:00`);return isNaN(d)?String(x):displayDate(d)};
const today=new Date();
let cycle=cycleKeyFromDate(today);
const defaults={version:3,cycles:{},expenses:[],recurring:[],savings:{balance:0,goal:72000,targetDate:"2028-09-30",wifeDefault:1500},savingsHistory:{}};
let state=structuredClone(defaults);
try{const raw=localStorage.getItem("money-plan-v3");if(raw)state={...defaults,...JSON.parse(raw)};else migrateV2()}catch(e){try{migrateV2()}catch(_){}}
function migrateV2(){try{const raw=localStorage.getItem("money-plan-v2");if(!raw)return;const v2=JSON.parse(raw);state={...structuredClone(defaults),version:3};const monthPlans=v2.plans||{};Object.entries(monthPlans).forEach(([ym,p])=>{const key=ym;state.cycles[key]={salary:p.income||0,carryIn:0,otherIncome:0,visa:0,threeOshour:0,spontaneous:0,mySaving:p.savings||0,wifeSaving:1500};});state.expenses=(v2.expenses||[]).map(e=>({...e,cycleKey:cycleKeyFromDate(new Date(`${e.date}T12:00:00`))}));state.recurring=(v2.recurring||[]).map(r=>({id:r.id,name:r.name,amount:r.amount,type:r.type,category:r.category||"Other",repeat:"forever",startCycle:cycle,cycles:0,active:r.active!==false}));if(v2.savings)state.savings={balance:v2.savings.current||0,goal:v2.savings.goal||72000,targetDate:"2028-09-30",wifeDefault:1500};save();}catch(e){}}
let syncTimer=null;
function save(){
  state.version=3;
  localStorage.setItem("money-plan-v3",JSON.stringify(state));
  try{window.MoneyPlanSync?.markLocalDirty();}catch(_){ }
  clearTimeout(syncTimer);
  syncTimer=setTimeout(()=>{try{window.MoneyPlanSync?.push();}catch(_){ }},700);
}
function ensureCycle(k=cycle){if(!state.cycles[k])state.cycles[k]={salary:0,carryIn:0,otherIncome:0,visa:0,threeOshour:0,spontaneous:0,mySaving:0,wifeSaving:state.savings.wifeDefault||1500};return state.cycles[k]}
const expenseCategories=["PayPal Später Bezahlen","One-off purchase","Unexpected / repair","Family","Other one-off"];
expenseCategories.forEach(x=>$('category').add(new Option(x,x)));
const recCats=["Housing","Utilities & bills","Insurance","Transport","Family","Food & groceries","Subscriptions","Other recurring"];
recCats.forEach(x=>$('rCat').add(new Option(x,x)));
function daysInCycle(k){return Math.round((cycleEnd(k)-cycleStart(k))/86400000)+1}
function cycleExpenses(k){return state.expenses.filter(e=>e.cycleKey===k||(!e.cycleKey&&cycleKeyFromDate(new Date(`${e.date}T12:00:00`))===k))}
function recurringActive(r,k){if(!r.active)return false;const start=r.startCycle||cycle;const [sy,sm]=start.split("-").map(Number),[ky,km]=k.split("-").map(Number);const idx=(ky-sy)*12+(km-sm)+1;if(idx<1)return false;if(r.repeat==="limited"&&idx>Number(r.cycles||0))return false;return true}
function recurringFor(k,type){return state.recurring.filter(r=>r.type===type&&recurringActive(r,k))}
function recurringTotal(k,type){return recurringFor(k,type).reduce((a,r)=>a+Number(r.amount||0),0)}
function getPlan(k=cycle){const c=ensureCycle(k);const oneoffs=cycleExpenses(k).reduce((a,e)=>a+Number(e.amount||0),0);const recurringExp=recurringTotal(k,"expense");const variable=Number(c.visa||0)+Number(c.threeOshour||0)+Number(c.spontaneous||0);const savings=Number(c.mySaving||0);const wife=Number(c.wifeSaving||0);const income=Number(c.salary||0)+Number(c.carryIn||0)+Number(c.otherIncome||0)+recurringTotal(k,"income");return{...c,oneoffs,recurringExp,variable,savings,wife,totalSaving:savings+wife,income,expectedOutflows:recurringExp+variable+oneoffs+savings,expectedLeftover:income-(recurringExp+variable+oneoffs+savings)}}
function nextCycleKey(k){const s=cycleStart(k);s.setMonth(s.getMonth()+1);return `${s.getFullYear()}-${pad(s.getMonth()+1)}`}
function prevCycleKey(k){const s=cycleStart(k);s.setMonth(s.getMonth()-1);return `${s.getFullYear()}-${pad(s.getMonth()+1)}`}
function shiftCycle(k,n){const s=cycleStart(k);s.setMonth(s.getMonth()+n);return `${s.getFullYear()}-${pad(s.getMonth()+1)}`}
function currentDayNumber(k){const s=cycleStart(k),e=cycleEnd(k);if(cycle!==cycleKeyFromDate(today))return 0;return Math.max(1,Math.min(daysInCycle(k),Math.floor((today-s)/86400000)+1))}
function showScreen(id){document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('active',s.id===id));document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.screen===id));if(id==='expenses')renderExpenses();if(id==='plan'){loadPlan();renderRecurring()}if(id==='savingsScreen'){loadSavings();renderSavings()}render()}
document.querySelectorAll('.nav button,[data-screen]').forEach(b=>b.addEventListener('click',()=>showScreen(b.dataset.screen)));
document.querySelectorAll('[data-cycle]').forEach(b=>b.addEventListener('click',()=>{cycle=shiftCycle(cycle,Number(b.dataset.cycle));ensureCycle();render();loadPlan();renderExpenses();renderRecurring()}));
$('fab').onclick=()=>{showScreen('expenses');$('amount').focus()};
$('help').onclick=()=>alert('Money Plan V3 uses your real financial cycle: salary date (normally the 25th) through the 24th. Salary, carry-in and other income create available money. Recurring commitments are included automatically. Visa, 3oshour and spontaneous spending are entered per cycle. Your Revolut saving contribution reduces cash available but is tracked separately toward the €72,000 university goal.');
$('addExpense').onclick=()=>{const amount=Math.max(0,Number($('amount').value)||0),date=$('date').value;if(!amount||!date)return;const ck=cycleKeyFromDate(new Date(`${date}T12:00:00`));state.expenses.push({id:Date.now(),date,amount,category:$('category').value,note:$('note').value.trim(),cycleKey:ck});save();$('amount').value='';$('note').value='';toast('One-off expense added');render();renderExpenses()};
function loadPlan(){const c=ensureCycle();['salary','carryIn','otherIncome','visa','threeOshour','spontaneous','mySaving','wifeSaving'].forEach(k=>$(k).value=c[k]??0);$('planCycle').textContent=`${cycleLabel(cycle)} · ${displayDate(cycleStart(cycle))} → ${displayDate(cycleEnd(cycle))}`;$('rStart').value=cycle;$('rStartHint').textContent=`This is the ${cycleLabel(cycle)} financial cycle: ${displayDate(cycleStart(cycle))} → ${displayDate(cycleEnd(cycle))}.`}
$('saveCycle').onclick=()=>{const c=ensureCycle();Object.assign(c,{salary:n('salary'),carryIn:n('carryIn'),otherIncome:n('otherIncome'),visa:n('visa'),threeOshour:n('threeOshour'),spontaneous:n('spontaneous'),mySaving:n('mySaving'),wifeSaving:n('wifeSaving')});save();toast('Cycle plan saved');render()};
$('rRepeat').onchange=()=>{$('rCountWrap').style.display=$('rRepeat').value==='limited'?'grid':'none';$('addCommitment').textContent=$('rRepeat').value==='limited'?'Add installment':'Add recurring item'};
$('rStart').onchange=()=>{const k=$('rStart').value||cycle;$('rStartHint').textContent=`This is the ${cycleLabel(k)} financial cycle: ${displayDate(cycleStart(k))} → ${displayDate(cycleEnd(k))}.`};
$('recForm').onsubmit=e=>{e.preventDefault();const name=$('rName').value.trim(),amount=n('rAmount');if(!name||!amount)return;const repeat=$('rRepeat').value,start=$('rStart').value||cycle;state.recurring.push({id:Date.now(),name,amount,type:$('rType').value,repeat,startCycle:start,cycles:repeat==='limited'?Math.max(1,parseInt($('rCount').value||'1',10)):0,category:$('rCat').value,active:true});save();e.target.reset();$('rStart').value=cycle;$('rStartHint').textContent=`This is the ${cycleLabel(cycle)} financial cycle: ${displayDate(cycleStart(cycle))} → ${displayDate(cycleEnd(cycle))}.`;$('rCountWrap').style.display='grid';renderRecurring();render();toast('Commitment added')};
function renderRecurring(){$('recurring').innerHTML=state.recurring.map((r,i)=>{const active=recurringActive(r,cycle);let extra=r.repeat==='limited'?` · ${r.cycles} cycles from ${cycleLabel(r.startCycle)} (${displayDate(cycleStart(r.startCycle))} → ${displayDate(cycleEnd(r.startCycle))})`:' · every cycle';let kind=r.repeat==='limited'?'Installment':'Recurring';return `<div class="rec-row"><div><b>${esc(r.name)}</b><div class="muted">${kind} · ${r.type==='income'?'Income':'Expense'} · ${esc(r.category)}${extra}</div></div><div><b>${money(r.amount)}</b><br><button class="delete" data-rec="${i}">${active?'Delete':'Remove'}</button></div></div>`}).join('')||'<span class="muted">No recurring items yet.</span>';document.querySelectorAll('[data-rec]').forEach(b=>b.onclick=()=>{state.recurring.splice(Number(b.dataset.rec),1);save();renderRecurring();render()})}
function n(id){return Math.max(0,Number($(id).value)||0)}
$('saveSavings').onclick=()=>{state.savings={balance:n('sBalance'),goal:n('sGoal'),targetDate:$('sTarget').value||'2028-09-30',wifeDefault:n('sWifeDefault')};save();toast('Savings settings saved');renderSavings();render()};
function loadSavings(){const s=state.savings;$('sBalance').value=s.balance||0;$('sGoal').value=s.goal||72000;$('sTarget').value=s.targetDate||'2028-09-30';$('sWifeDefault').value=s.wifeDefault??1500}
function cycleTargetDate(){return new Date(`${state.savings.targetDate||'2028-09-30'}T12:00:00`)}
function monthsBetween(a,b){return Math.max(0,(b.getFullYear()-a.getFullYear())*12+(b.getMonth()-a.getMonth())+(b.getDate()>=a.getDate()?0: -1))}
function savingsMetrics(){const s=state.savings,balance=Number(s.balance||0),goal=Number(s.goal||0),target=cycleTargetDate();const start=cycleStart(cycle);const monthsLeft=Math.max(0,monthsBetween(start,target));const remaining=Math.max(0,goal-balance);const required=monthsLeft>0?remaining/monthsLeft:remaining;const totalUser=Object.values(state.cycles).reduce((a,c)=>a+Number(c.mySaving||0),0);const totalWife=Object.values(state.cycles).reduce((a,c)=>a+Number(c.wifeSaving||0),0);const targetPerCycle=monthsLeft>0?remaining/monthsLeft:remaining;const currentCycle=ensureCycle();const plannedThisCycle=Number(currentCycle.mySaving||0)+Number(currentCycle.wifeSaving||0);const aheadBehind=plannedThisCycle-targetPerCycle;const baseline3000=3000;const contributionVsBaseline=plannedThisCycle-baseline3000;return{balance,goal,target,monthsLeft,remaining,required,totalUser,totalWife,targetPerCycle,plannedThisCycle,aheadBehind,contributionVsBaseline}}
function render(){const p=getPlan(cycle),start=cycleStart(cycle),end=cycleEnd(cycle),days=daysInCycle(cycle),isCurrent=cycle===cycleKeyFromDate(today),day=isCurrent?currentDayNumber(cycle):days;const elapsed=Math.max(1,day),remainingDays=Math.max(1,days-day+1);const spentOneoff=p.oneoffs;const variable=p.variable;const spentKnown=p.recurringExp+variable+spentOneoff+p.savings;const daily=Math.max(0,p.expectedLeftover)/remainingDays;const available=p.income;const expected=p.expectedOutflows;const leftover=p.expectedLeftover;const used=Math.min(100,available?Math.max(0,(expected/available)*100):0);$('cycleTitle').textContent=cycleLabel(cycle);$('cycleDates').textContent=`${displayDate(start)} → ${displayDate(end)}`;$('expenseCycle').textContent=`${cycleLabel(cycle)} · ${displayDate(start)} → ${displayDate(end)}`;$('planCycle').textContent=`${cycleLabel(cycle)} · ${displayDate(start)} → ${displayDate(end)}`;$('remaining').textContent=money(leftover);$('remainingBar').style.width=used+'%';$('remainingMessage').textContent=leftover>=0?`${money(expected)} planned outflows from ${money(available)} available.`:`Your plan is ${money(Math.abs(leftover))} over the money available for this cycle.`;$('dailyAllowance').textContent=money(daily);const todayOneoffs=cycleExpenses(cycle).filter(e=>e.date===iso(today)).reduce((a,e)=>a+Number(e.amount||0),0);const dailyDelta=daily-todayOneoffs;$('dailyStatus').className='mini-status '+(dailyDelta>=0?'ok':'bad');$('dailyStatus').textContent=isCurrent?(dailyDelta>=0?`${money(dailyDelta)} of today's capacity remains`:`${money(Math.abs(dailyDelta))} above today's capacity`):'Select the current cycle to see today\'s capacity';$('available').textContent=money(available);$('recurringTotal').textContent=money(p.recurringExp);$('variableTotal').textContent=money(variable+p.oneoffs);$('savingOutflow').textContent=money(p.savings);$('expectedOutflows').textContent=money(expected);$('expectedLeftover').textContent=money(leftover);$('nextCarry').textContent=money(Math.max(0,leftover));const badge=$('forecastBadge');badge.className='badge '+(leftover>=0?'good':'bad');badge.textContent=leftover>=0?'Within cash available':'Over available cash';$('forecastText').textContent=leftover>=0?`If nothing else changes, ${money(leftover)} will carry into the next financial cycle.`:`Reduce planned outflows by ${money(Math.abs(leftover))}, increase income, or reduce the savings contribution.`;
const rows=[['Salary / main income',p.salary],['Previous cycle leftover',p.carryIn],['Other income',p.otherIncome],['Recurring income',recurringTotal(cycle,'income')],['Recurring commitments',-p.recurringExp],['Visa',-p.visa],['3oshour',-p.threeOshour],['Spontaneous',-p.spontaneous],['One-off expenses',-p.oneoffs],['Your Revolut saving',-p.savings]];$('cycleBreakdown').innerHTML=rows.map(([l,v])=>`<div class="split"><span>${l}</span><b class="${v<0?'negative':v>0?'positive':''}">${v<0?'−':''}${money(Math.abs(v))}</b></div>`).join('')+`<div class="split"><span><b>Expected leftover</b></span><b class="${leftover<0?'negative':'positive'}">${money(leftover)}</b></div>`;
const sm=savingsMetrics();$('homeSavings').innerHTML=`<div class="split"><span>Current balance</span><b>${money(sm.balance)}</b></div><div class="split"><span>Target</span><b>${money(sm.goal)}</b></div><div class="split"><span>Required average from here</span><b>${money(sm.required)}/cycle</b></div><div class="status-box ${sm.balance>=sm.goal&&sm.goal>0?'good':sm.aheadBehind>=0?'good':'warn'}"><b>${sm.balance>=sm.goal?'Goal reached':sm.aheadBehind>=0?'Current cycle contribution is on/above trajectory':'Current cycle contribution is below trajectory'}</b><div class="muted">Your + wife contributions are tracked separately from spending.</div></div>`;
const recent=cycleExpenses(cycle).slice().sort((a,b)=>b.date.localeCompare(a.date));$('recent').innerHTML=recent.slice(0,6).map(e=>`<div class="expense-row"><div class="expense-meta"><b>${esc(e.category)}</b><span>${displayIsoDate(e.date)}${e.note?' · '+esc(e.note):''}</span></div><div><span class="amount">${money(e.amount)}</span></div></div>`).join('')||'<span class="muted">No one-off expenses in this cycle.</span>';
const planned= p.recurringExp+p.variable+p.oneoffs+p.savings;const buffer= p.income-planned;$('planReality').innerHTML=`<div class="forecast-grid"><div><span>Available</span><b>${money(p.income)}</b></div><div><span>Outflows</span><b>${money(planned)}</b></div><div><span>Leftover</span><b>${money(buffer)}</b></div></div><p class="${buffer<0?'negative':'positive'}"><b>${buffer<0?'Cycle plan exceeds available money by ':'Expected carry-over: '}${money(Math.abs(buffer))}</b></p><p class="muted">Recurring expenses are already treated as paid. One-off expenses and your variable monthly amounts are added on top.</p>`;
}
function renderExpenses(){$('expenseList').innerHTML=cycleExpenses(cycle).slice().sort((a,b)=>b.date.localeCompare(a.date)).map(e=>`<div class="expense-row"><div class="expense-meta"><b>${esc(e.category)}</b><span>${displayIsoDate(e.date)}${e.note?' · '+esc(e.note):''}</span></div><div><span class="amount">${money(e.amount)}</span><br><button class="delete" data-del="${e.id}">Delete</button></div></div>`).join('')||'<span class="muted">No one-off expenses for this cycle.</span>';document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{state.expenses=state.expenses.filter(e=>String(e.id)!==b.dataset.del);save();renderExpenses();render()})}
function renderSavings(){const sm=savingsMetrics(),goal=sm.goal,balance=sm.balance,pct=goal?Math.min(100,balance/goal*100):0;$('goalValue').textContent=money(balance);$('goalBar').style.width=pct+'%';const status=balance>=goal?'Goal reached':sm.aheadBehind>=0?'On/above the required trajectory':'Below the required trajectory';$('goalText').textContent=`${Math.round(pct)}% · ${money(Math.max(0,goal-balance))} remaining · ${status}`;$('savingsStatus').innerHTML=`<div class="status-box ${balance>=goal||sm.aheadBehind>=0?'good':'warn'}"><div class="big-number">${balance>=goal?'Ahead / complete':sm.aheadBehind>=0?'On track this cycle':'Behind this cycle'}</div><p class="muted">Target date: ${displayDate(sm.target)}. Required average from the current cycle: <b>${money(sm.required)}</b> per cycle.</p><p class="muted">This cycle: you ${money(ensureCycle().mySaving||0)} + wife ${money(ensureCycle().wifeSaving||0)} = <b>${money(sm.plannedThisCycle)}</b>. Required average from here: <b>${money(sm.required)}</b>.</p></div>`;
const hist=Object.entries(state.cycles).filter(([k,c])=>Number(c.mySaving||0)+Number(c.wifeSaving||0)>0).sort(([a],[b])=>b.localeCompare(a));$('savingsHistory').innerHTML=hist.map(([k,c])=>`<div class="split"><span>${cycleLabel(k)}<small class="muted">${displayDate(cycleStart(k))} → ${displayDate(cycleEnd(k))}</small></span><b>${money(Number(c.mySaving||0)+Number(c.wifeSaving||0))}<br><small class="muted">You ${money(c.mySaving||0)} · Wife ${money(c.wifeSaving||0)}</small></b></div>`).join('')||'<span class="muted">No contribution history yet.</span>';
const rows=[];let running=balance;for(let i=0;i<12;i++){const k=shiftCycle(cycle,i),c=ensureCycle(k),con=Number(c.mySaving||0)+Number(c.wifeSaving||0);if(i===0)running=balance;else running+=con;const pct2=goal?Math.min(100,running/goal*100):0;rows.push(`<div class="budget"><div class="budget-label"><span>${cycleLabel(k)}</span><b>${money(running)}</b></div><div class="bar"><i style="width:${pct2}%"></i></div></div>`)}$('projection').innerHTML=rows.join('')}
function loadSavings(){const s=state.savings;$('sBalance').value=s.balance||0;$('sGoal').value=s.goal||72000;$('sTarget').value=s.targetDate||'2028-09-30';$('sWifeDefault').value=s.wifeDefault??1500}
$('export').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`money-plan-v3-backup-${iso(new Date())}.json`;a.click();URL.revokeObjectURL(url);toast('V3 backup exported')};
$('importBtn').onclick=()=>$('importFile').click();$('importFile').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!x.cycles||!x.expenses||!x.savings)throw new Error();state={...structuredClone(defaults),...x,version:3};try{window.MoneyPlanSync?.clearMigrationMarker?.();}catch(_){}save();loadPlan();loadSavings();renderRecurring();renderExpenses();render();toast('V3 backup restored')}catch(_){alert('That backup file is not a valid Money Plan V3 backup.')}};r.readAsText(f)};
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),1800)}
function updateSyncUI(detail={}){
  const status=$('syncStatus'), signedOut=$('syncSignedOut'), signedIn=$('syncSignedIn'), email=$('syncUserEmail'), conflict=$('syncConflictText');
  if(!status)return;
  const u=window.MoneyPlanSync?.getUser?.();
  if(detail.status==='unconfigured'){status.textContent='Cloud sync: not configured — local-only mode';status.className='sync-status warn';}
  else if(detail.status==='error'){status.textContent='Cloud sync: error — '+(detail.message||'check Firebase setup');status.className='sync-status warn';}
  else if(detail.status==='conflict'){status.textContent='Cloud sync: conflict detected — review before continuing';status.className='sync-status warn';}
  else if(detail.status==='migration'){status.textContent='Cloud sync: migration choice required';status.className='sync-status warn';}
  else if(detail.status==='syncing'){status.textContent='Cloud sync: synchronizing…';status.className='sync-status';}
  else if(detail.status==='synced'){status.textContent='Cloud sync: synchronized';status.className='sync-status good';}
  else if(u){status.textContent='Cloud sync: signed in';status.className='sync-status good';}
  if(signedOut)signedOut.style.display=u?'none':'block';
  if(signedIn)signedIn.style.display=u?'block':'none';
  if(email)email.textContent=u?.email||'';
  if(conflict){const count=(window.MoneyPlanSync?.getConflicts?.()||[]).length;conflict.textContent=count?`${count} conflict notice${count===1?'':'s'} stored locally.`:'No conflict notices.';}
}
function migrationSummary(x){if(!x)return '';return `${x.cycles} cycles · ${x.expenses} expenses · ${x.recurring} recurring/installments · ${x.savingsHistory} savings history · savings balance ${money(x.savingsBalance)}`;}
function showMigration(detail={}){const m=$('migrationModal');if(!m)return;$('migrationLocalSummary').textContent=migrationSummary(detail.local);$('migrationRemoteSummary').textContent=migrationSummary(detail.remote);m.style.display='flex';}
function hideMigration(){$('migrationModal')?.style.setProperty('display','none');}
$('migrationKeepLocal')?.addEventListener('click',async()=>{try{await window.MoneyPlanSync.resolveMigration('local');hideMigration();toast('Device data uploaded to cloud');}catch(e){alert(e.message||'Migration failed')}});
$('migrationKeepCloud')?.addEventListener('click',async()=>{try{await window.MoneyPlanSync.resolveMigration('cloud');hideMigration();toast('Cloud data loaded to this device');}catch(e){alert(e.message||'Migration failed')}});
$('migrationCancel')?.addEventListener('click',async()=>{hideMigration();try{await window.MoneyPlanSync.signOut();}catch(_){}});
window.addEventListener('moneyplan:migration-needed',e=>showMigration(e.detail));
window.addEventListener('moneyplan:sync-status',e=>updateSyncUI(e.detail));
window.addEventListener('moneyplan:conflict',()=>updateSyncUI({status:'conflict'}));
window.addEventListener('moneyplan:conflict-cleared',()=>updateSyncUI({}));
window.addEventListener('moneyplan:remote-applied',()=>{try{state={...structuredClone(defaults),...JSON.parse(localStorage.getItem('money-plan-v3'))};loadPlan();loadSavings();renderRecurring();render();renderExpenses();toast('Synced from cloud')}catch(_){}});
$('syncSignIn')?.addEventListener('click',async()=>{try{await window.MoneyPlanSync.signIn($('syncEmail').value.trim(),$('syncPassword').value);toast('Signed in');}catch(e){alert(e.message||'Sign-in failed')}});
$('syncSignUp')?.addEventListener('click',async()=>{try{await window.MoneyPlanSync.signUp($('syncEmail').value.trim(),$('syncPassword').value);toast('Account created');}catch(e){alert(e.message||'Account creation failed')}});
$('syncReset')?.addEventListener('click',async()=>{try{await window.MoneyPlanSync.resetPassword($('syncEmail').value.trim());toast('Password reset email sent');}catch(e){alert(e.message||'Password reset failed')}});
$('syncSignOut')?.addEventListener('click',async()=>{try{await window.MoneyPlanSync.signOut();toast('Signed out');updateSyncUI({});}catch(e){alert(e.message||'Sign-out failed')}});
$('syncNow')?.addEventListener('click',async()=>{try{await window.MoneyPlanSync.push();toast('Sync complete');}catch(e){alert(e.message||'Sync failed')}});
$('syncClearConflicts')?.addEventListener('click',()=>{window.MoneyPlanSync?.clearConflicts();updateSyncUI({});});
$('date').value=iso(today);$('rStart').value=cycle;$('rCountWrap').style.display='none';$('addCommitment').textContent='Add recurring item';loadPlan();loadSavings();renderRecurring();render();renderExpenses();renderSavings();
updateSyncUI({});
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
})();
